product_features:
  get:
    operationId: features_list_product
    summary: List features in a product
    description: |
      Returns a list of features associated with a specific product.
    tags:
      - Features
    parameters:
      - name: product_id
        in: path
        required: true
        schema:
          type: string
        description: Numeric ID or key of the product
      - name: q
        in: query
        description: Search term to match against feature name
        required: false
        schema:
          type: string
      - name: updated_since
        in: query
        description: >-
          UTC timestamp (in ISO8601 format). If provided, only features updated
          after the timestamp will be returned
        required: false
        schema:
          type: string
          format: date-time
      - name: tag
        in: query
        description: >-
          String tag value. If provided, only features with the associated tag
          will be returned
        required: false
        schema:
          type: string
      - name: assigned_to_user
        in: query
        description: >-
          ID or email address of a user. If provided, only features assigned to
          that user will be returned
        required: false
        schema:
          type: string
      - name: page
        in: query
        required: false
        schema:
          type: integer
          default: 1
        description: Page number for pagination
      - name: per_page
        in: query
        required: false
        schema:
          type: integer
          default: 20
        description: Number of features per page
    responses:
      '200':
        description: A list of features in the product
        content:
          application/json:
            schema:
              $ref: >-
                ../../schemas/features/list_response.yaml#/FeaturesListResponse
      '401':
        description: Unauthorized
      '403':
        description: Forbidden
      '404':
        description: Product not found
