---
# ignore the version error
openapi: 3.0.3
info:
  title: Aha! REST API
  description: API for interacting with Aha! product management platform.
  version: 1.0.0

servers:
  - url: https://{subdomain}.aha.io/api/v1
    description: Aha! API server
    variables:
      subdomain:
        default: mycompany
        description: Your Aha! account subdomain

# Paths are referenced from separate files
paths:
  # Users
  /users:
    $ref: './paths/users.yaml#/users'
  /users/{id}:
    $ref: './paths/users.yaml#/users_by_id'

  # Features
  /features:
    $ref: './paths/features/list.yaml#/list_features'
  /goals/{goal_id}/features:
    $ref: './paths/features/goal_features_path.yaml#/goal_features_path'
  /initiatives/{initiative_id}/features:
    $ref: './paths/features/initiative_features_path.yaml#/initiative_features_path'
  /products/{product_id}/features:
    $ref: './paths/features/product_features_path.yaml#/product_features_path'
  /releases/{release_id}/features:
    $ref: './paths/features/release_features_path.yaml#/release_features_path'
  /features/{id}:
    $ref: './paths/features/feature_by_id_path.yaml#/feature_by_id_path'
  /features/{id}/custom_fields:
    $ref: './paths/features/feature_custom_fields_path.yaml#/feature_custom_fields_path'
  /features/{id}/custom_fields/tag:
    $ref: './paths/features/feature_custom_fields_tag_path.yaml#/feature_custom_fields_tag_path'
  /features/{id}/custom_fields/worksheet:
    $ref: './paths/features/feature_custom_worksheet_fields_path.yaml#/feature_custom_worksheet_fields_path'
  /features/{id}/epic:
    $ref: './paths/features/feature_epic_path.yaml#/feature_epic_path'
  /features/{id}/goals:
    $ref: './paths/features/feature_goals_path.yaml#/feature_goals_path'
  /features/{id}/progress:
    $ref: './paths/features/feature_progress_path.yaml#/feature_progress_path'
  /features/{id}/progress_source:
    $ref: './paths/features/feature_progress_source_path.yaml#/feature_progress_source_path'
  /features/{id}/release:
    $ref: './paths/features/feature_release_path.yaml#/feature_release_path'
  /features/{id}/score:
    $ref: './paths/features/feature_score_path.yaml#/feature_score_path'
  /features/{id}/tags:
    $ref: './paths/features/feature_tags_array_path.yaml#/feature_tags_array_path'
  /features/{id}/convert_to_epic:
    $ref: './paths/features/feature_convert_to_epic_path.yaml#/feature_convert_to_epic_path'

  # Comments
  /features/{feature_id}/comments:
    $ref: './paths/comments.yaml#/feature_comments'
  /epics/{epic_id}/comments:
    $ref: './paths/comments.yaml#/epic_comments'
  /requirements/{requirement_id}/comments:
    $ref: './paths/comments.yaml#/requirement_comments'
  /ideas/{idea_id}/comments:
    $ref: './paths/comments.yaml#/idea_comments'
  /initiatives/{initiative_id}/comments:
    $ref: './paths/comments.yaml#/initiative_comments'
  /goals/{goal_id}/comments:
    $ref: './paths/comments.yaml#/goal_comments'
  /releases/{release_id}/comments:
    $ref: './paths/comments.yaml#/release_comments'
  /release_phases/{release_phase_id}/comments:
    $ref: './paths/comments.yaml#/release_phase_comments'
  /todos/{todo_id}/comments:
    $ref: './paths/comments.yaml#/todo_comments'
  /products/{product_id}/comments:
    $ref: './paths/comments.yaml#/product_comments'

  # Epics
  /products/{product_id}/epics:
    $ref: './paths/epics.yaml#/product_epics'
  /releases/{release_id}/epics:
    $ref: './paths/epics.yaml#/release_epics'
  /epics/{epic_id}:
    $ref: './paths/epics.yaml#/epic_by_id'
  /epics/{epic_id}/features:
    $ref: './paths/features/epic_features_path.yaml#/epic_features_path'
  /goals/{goal_id}/epics:
    $ref: './paths/epics.yaml#/goal_epics'
  /initiatives/{initiative_id}/epics:
    $ref: './paths/epics.yaml#/initiative_epics'

  # Competitors
  /products/{product_id}/competitors:
    $ref: './paths/competitors.yaml#/product_competitors'
  /competitors/{competitor_id}:
    $ref: './paths/competitors.yaml#/competitor_by_id'

  # Products
  /products:
    $ref: './paths/products/list.yaml#/list_products'

  # Initiatives
  /initiatives:
    $ref: './paths/initiatives/list.yaml#/list_initiatives'
  /products/{product_id}/initiatives:
    $ref: './paths/initiatives/create.yaml#/product_initiatives_path'
  /initiatives/{id}:
    $ref: './paths/initiatives/get.yaml#/initiative_by_id_path'

  # Ideas
  /products/{product_id}/ideas:
    $ref: './paths/ideas/product_ideas_path.yaml#/product_ideas_path'
  /products/{product_id}/ideas/portal_user:
    $ref: './paths/ideas/create_by_portal_user.yaml#/product_ideas_portal_user_path'
  /products/{product_id}/ideas/with_category:
    $ref: './paths/ideas/create_with_category.yaml#/product_ideas_with_category_path'
  /products/{product_id}/ideas/with_score:
    $ref: './paths/ideas/create_with_score.yaml#/product_ideas_with_score_path'
  /ideas/{id}:
    $ref: './paths/ideas/idea_by_id_path.yaml#/idea_by_id_path'

  # Releases
  /releases:
    $ref: './paths/releases/list.yaml#/list_releases'
  /products/{product_id}/releases:
    $ref: './paths/releases/product_releases.yaml#/product_releases'
  /releases/{id}:
    $ref: './paths/releases/get.yaml#/release_by_id_path'

  # Goals
  /goals:
    $ref: './paths/goals/list.yaml#/goals_path'
  /goals/{id}:
    $ref: './paths/goals/get.yaml#/goal_by_id_path'
  /goals/{id}/progress:
    $ref: './paths/goals/progress.yaml#/goal_progress_path'

  # Strategic Models
  /strategic_models:
    $ref: './paths/strategic_models/list.yaml#/strategic_models_path'
  /strategic_models/{id}:
    $ref: './paths/strategic_models/get.yaml#/strategic_model_by_id_path'

# Components are referenced from separate files
components:
  schemas:
    # User related schemas
    User:
      $ref: './schemas/users.yaml#/User'

    # Feature related schemas
    FeatureCreateRequest:
      $ref: './schemas/features/create_request.yaml#/FeatureCreateRequest'
    Feature:
      $ref: './schemas/features/feature.yaml#/Feature'
    FeaturesListResponse:
      $ref: './schemas/features/list_response.yaml#/FeaturesListResponse'
    FeatureGetResponse:
      $ref: './schemas/features/get_response.yaml#/FeatureGetResponse'

    # Comment related schemas
    CommentCreateRequest:
      $ref: './schemas/comments.yaml#/CommentCreateRequest'
    Comment:
      $ref: './schemas/comments.yaml#/Comment'

    # Competitor related schemas
    CompetitorCreateRequest:
      $ref: './schemas/competitors.yaml#/CompetitorCreateRequest'
    CompetitorUpdateRequest:
      $ref: './schemas/competitors.yaml#/CompetitorUpdateRequest'
    Competitor:
      $ref: './schemas/competitors.yaml#/Competitor'

    # Epic related schemas
    EpicUpdateRequest:
      $ref: './schemas/epics.yaml#/EpicUpdateRequest'
    EpicCreateRequest:
      $ref: './schemas/epics.yaml#/EpicCreateRequest'
    Epic:
      $ref: './schemas/epics.yaml#/Epic'

    # Idea related schemas
    IdeaCreateRequest:
      $ref: './schemas/ideas/create_request.yaml#/IdeaCreateRequest'
    IdeaCreateByPortalUserRequest:
      $ref: './schemas/ideas/create_by_portal_user_request.yaml#/IdeaCreateByPortalUserRequest'
    IdeaResponse:
      $ref: './schemas/ideas/idea.yaml#/IdeaResponse'
    IdeasListResponse:
      $ref: './schemas/ideas/list_response.yaml#/IdeasListResponse'

    # Product related schemas
    ProductsListResponse:
      $ref: './schemas/products/list_response.yaml#/ProductsListResponse'

    # Initiative related schemas
    InitiativeCreateRequest:
      $ref: './schemas/initiatives/create_request.yaml#/InitiativeCreateRequest'
    InitiativeResponse:
      $ref: './schemas/initiatives/initiative.yaml#/InitiativeResponse'
    InitiativesListResponse:
      $ref: './schemas/initiatives/list_response.yaml#/InitiativesListResponse'

    # Release related schemas
    ReleaseCreateRequest:
      $ref: './schemas/releases/create_request.yaml#/ReleaseCreateRequest'
    ReleaseUpdateRequest:
      $ref: './schemas/releases/update_request.yaml#/ReleaseUpdateRequest'
    Release:
      $ref: './schemas/releases/release.yaml#/Release'
    ReleaseGetResponse:
      $ref: './schemas/releases/get_response.yaml#/ReleaseGetResponse'
    ReleasesListResponse:
      $ref: './schemas/releases/list_response.yaml#/ReleasesListResponse'

    # Goal related schemas
    GoalCreateRequest:
      $ref: './schemas/goals/create_request.yaml#/GoalCreateRequest'
    GoalUpdateRequest:
      $ref: './schemas/goals/update_request.yaml#/GoalUpdateRequest'
    GoalProgressUpdateRequest:
      $ref: './schemas/goals/progress_update_request.yaml#/GoalProgressUpdateRequest'
    Goal:
      $ref: './schemas/goals/goal.yaml#/Goal'
    GoalGetResponse:
      $ref: './schemas/goals/get_response.yaml#/GoalGetResponse'
    GoalsListResponse:
      $ref: './schemas/goals/list_response.yaml#/GoalsListResponse'

    # Strategic Model related schemas
    StrategicModelCreateRequest:
      $ref: './schemas/strategic_models/create_request.yaml#/StrategicModelCreateRequest'
    StrategicModelUpdateRequest:
      $ref: './schemas/strategic_models/update_request.yaml#/StrategicModelUpdateRequest'
    StrategicModel:
      $ref: './schemas/strategic_models/strategic_model.yaml#/StrategicModel'
    StrategicModelGetResponse:
      $ref: './schemas/strategic_models/get_response.yaml#/StrategicModelGetResponse'
    StrategicModelsListResponse:
      $ref: './schemas/strategic_models/list_response.yaml#/StrategicModelsListResponse'

  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://{subdomain}.aha.io/oauth/authorize
          tokenUrl: https://{subdomain}.aha.io/oauth/token
          scopes: {}
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - OAuth2: []
  - BearerAuth: []

tags:
  - name: Competitors
  - name: Users
  - name: Features
  - name: Releases
  - name: Comments
  - name: Epics
  - name: Requirements
  - name: Ideas
  - name: Initiatives
  - name: Goals
  - name: Strategic Models
  - name: Release Phases
  - name: Todos
  - name: Products
