openapi: 3.0.3
info:
  title: Aha! REST API
  description: API for interacting with Aha! product management platform.
  version: 1.0.0

servers:
  - url: https://{subdomain}.aha.io/api/v1
    description: Aha! API server
    variables:
      subdomain:
        default: mycompany
        description: Your Aha! account subdomain

# Paths are referenced from separate files
paths:
  # Users
  /users:
    $ref: './paths/users.yaml#/users'
  /users/{id}:
    $ref: './paths/users.yaml#/users_by_id'

  # Features
  /features:
    $ref: './paths/features/index.yaml#/list_features'
  /goals/{goal_id}/features:
    $ref: './paths/features/index.yaml#/goal_features'
  /initiatives/{initiative_id}/features:
    $ref: './paths/features/index.yaml#/initiative_features'
  /products/{product_id}/features:
    $ref: './paths/features/index.yaml#/product_features'
  /releases/{release_id}/features:
    post:
      $ref: './paths/features/index.yaml#/release_features'
    get:
      $ref: './paths/features/index.yaml#/release_features_get'
  /features/{id}:
    get:
      $ref: './paths/features/index.yaml#/get_feature'
    put:
      $ref: './paths/features/index.yaml#/update_feature'
    delete:
      $ref: './paths/features/index.yaml#/delete_feature'
  /features/{id}/custom_fields:
    put:
      $ref: './paths/features/index.yaml#/update_feature_custom_fields'
  /features/{id}/custom_fields/tag:
    put:
      $ref: './paths/features/index.yaml#/update_feature_custom_fields_tag'
  /features/{id}/custom_fields/worksheet:
    put:
      $ref: './paths/features/index.yaml#/update_feature_custom_worksheet_fields'
  /features/{id}/epic:
    put:
      $ref: './paths/features/index.yaml#/update_feature_epic'
  /features/{id}/goals:
    put:
      $ref: './paths/features/index.yaml#/update_feature_goals'
  /features/{id}/progress:
    put:
      $ref: './paths/features/index.yaml#/update_feature_progress'
  /features/{id}/convert_to_epic:
    $ref: './paths/features/index.yaml#/convert_to_epic'

  # Comments
  /features/{feature_id}/comments:
    $ref: './paths/comments.yaml#/feature_comments'
  /epics/{epic_id}/comments:
    $ref: './paths/comments.yaml#/epic_comments'
  /requirements/{requirement_id}/comments:
    $ref: './paths/comments.yaml#/requirement_comments'
  /ideas/{idea_id}/comments:
    $ref: './paths/comments.yaml#/idea_comments'
  /initiatives/{initiative_id}/comments:
    $ref: './paths/comments.yaml#/initiative_comments'
  /goals/{goal_id}/comments:
    $ref: './paths/comments.yaml#/goal_comments'
  /releases/{release_id}/comments:
    $ref: './paths/comments.yaml#/release_comments'
  /release_phases/{release_phase_id}/comments:
    $ref: './paths/comments.yaml#/release_phase_comments'
  /todos/{todo_id}/comments:
    $ref: './paths/comments.yaml#/todo_comments'
  /products/{product_id}/comments:
    $ref: './paths/comments.yaml#/product_comments'

  # Epics
  /products/{product_id}/epics:
    $ref: './paths/epics.yaml#/product_epics'
  /releases/{release_id}/epics:
    $ref: './paths/epics.yaml#/release_epics'
  /epics/{epic_id}:
    $ref: './paths/epics.yaml#/epic_by_id'
  /epics/{epic_id}/features:
    $ref: './paths/features/index.yaml#/epic_features'
  /goals/{goal_id}/epics:
    $ref: './paths/epics.yaml#/goal_epics'
  /initiatives/{initiative_id}/epics:
    $ref: './paths/epics.yaml#/initiative_epics'

  # Competitors
  /products/{product_id}/competitors:
    $ref: './paths/competitors.yaml#/product_competitors'
  /competitors/{competitor_id}:
    $ref: './paths/competitors.yaml#/competitor_by_id'

# Components are referenced from separate files
components:
  schemas:
    # User related schemas
    User:
      $ref: './schemas/users.yaml#/User'

    # Feature related schemas
    FeatureCreateRequest:
      $ref: './schemas/features/index.yaml#/FeatureCreateRequest'
    Feature:
      $ref: './schemas/features/index.yaml#/Feature'
    FeaturesListResponse:
      $ref: './schemas/features/index.yaml#/FeaturesListResponse'
    FeatureGetResponse:
      $ref: './schemas/features/index.yaml#/FeatureGetResponse'

    # Comment related schemas
    CommentCreateRequest:
      $ref: './schemas/comments.yaml#/CommentCreateRequest'
    Comment:
      $ref: './schemas/comments.yaml#/Comment'

    # Competitor related schemas
    CompetitorCreateRequest:
      $ref: './schemas/competitors.yaml#/CompetitorCreateRequest'
    CompetitorUpdateRequest:
      $ref: './schemas/competitors.yaml#/CompetitorUpdateRequest'
    Competitor:
      $ref: './schemas/competitors.yaml#/Competitor'

    # Epic related schemas
    EpicUpdateRequest:
      $ref: './schemas/epics.yaml#/EpicUpdateRequest'
    EpicCreateRequest:
      $ref: './schemas/epics.yaml#/EpicCreateRequest'
    Epic:
      $ref: './schemas/epics.yaml#/Epic'

  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://{subdomain}.aha.io/oauth/authorize
          tokenUrl: https://{subdomain}.aha.io/oauth/token
          scopes: {}
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - OAuth2: []
  - BearerAuth: []

tags:
  - name: Competitors
  - name: Users
  - name: Features
  - name: Releases
  - name: Comments
  - name: Epics
  - name: Requirements
  - name: Ideas
  - name: Initiatives
  - name: Goals
  - name: Release Phases
  - name: Todos
  - name: Products
